name: Render and Update CV

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - "**.pdf"

jobs:
  render-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Test and Render
        uses: ./.github/actions/test-and-render
        with:
          file: cv/mle.yaml

      - name: Commit and push PDF file
        uses: ./.github/actions/git-commit-push
        with:
          files: cv/mle.typ cv/mle.pdf
