name: Update CV

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - "**.pdf"

jobs:
  render-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Render Rmarkdown
        uses: ./.github/actions/render-rmarkdown
        with:
          file: cv/mle.Rmd
      
      - name: Commit and push PDF file
        uses: ./.github/actions/git-commit-push
        with:
          files: cv/mle.pdf
